# =============================================================================
# NAMESPACE
# =============================================================================
# No Docker Compose, todos os containers compartilham uma "network".
# No Kubernetes, um Namespace é como um "projeto" que agrupa todos os recursos.
# Ele isola seus recursos dos demais no cluster.
# =============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: ragro
  labels:
    app.kubernetes.io/part-of: ragro
