-- Adds a 4-digit delivery confirmation code to orders.
-- The code is generated by the backend when an order transitions to IN_DELIVERY.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS confirmation_code VARCHAR(4);
