-- Adds a 4-digit delivery confirmation code to orders.
-- The code is generated by the backend when an order transitions to IN_DELIVERY.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS confirmation_code VARCHAR(4);

-- Enforce that confirmation_code, when present, contains exactly 4 digits.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'orders_confirmation_code_format_chk'
  ) THEN
    ALTER TABLE orders
      ADD CONSTRAINT orders_confirmation_code_format_chk
      CHECK (confirmation_code IS NULL OR confirmation_code ~ '^\d{4}$');
  END IF;
END $$;

-- Adds brute-force protection fields: attempt counter and lockout timestamp.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS confirmation_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS confirmation_locked_until TIMESTAMPTZ;
